/**
 * Full customer set: one distinct customer per service category (11 total),
 * each holding a single continuous 20-turn conversation.
 *
 * Turns are written to flow like a real B2B enquiry and deliberately use
 * pronouns and back-references ("that one", "the same fabric", "it") so that
 * context retention is exercised, not just single-shot answering. Every
 * conversation also probes the commercial-safety rails at least three times
 * (price / MOQ / delivery date / certification / wash claims).
 */

export const personas = [
  {
    name: "Rajesh Kumar",
    company: "Kumar Exports",
    service: "Emboss Printing",
    profile: "Garment exporter, polo shirts for European buyers",
    turns: [
      "Hi, I'm Rajesh from Kumar Exports. We manufacture polo shirts for European buyers.",
      "We want our brand logo on the left chest with a premium raised look. What would you suggest?",
      "How is emboss different from the silicone HD option?",
      "Let's go with emboss. Our fabric is 220 GSM pique cotton - will it hold the emboss properly?",
      "The logo is quite detailed, with some thin lettering. Is that a problem for it?",
      "What would you need from us to prepare the mould?",
      "How long does the mould preparation usually take?",
      "What would the price per piece be for 1000 polos with that?",
      "And what is your minimum order quantity?",
      "Can we get a sample before confirming the bulk order?",
      "What does the sample cost?",
      "We need delivery by 30th November. Is that achievable?",
      "Will the emboss survive industrial washing at 60 degrees?",
      "Do you have any Oeko-Tex or GOTS certification?",
      "Could we add a small foil detail on top of the emboss?",
      "Our buyer also wants a size tag print on the back neck. Can you do that too?",
      "What artwork format should I send you?",
      "Just to confirm, you have my company name already?",
      "Okay, please put together a quotation enquiry for us.",
      "And how do I reach your team directly if I need to follow up?",
    ],
  },
  {
    name: "Priya Venkatesan",
    company: "VStar Sportswear",
    service: "Sublimation Printing",
    profile: "Sportswear maker, all-over printed jerseys for clubs",
    turns: [
      "Hello, we make sports jerseys for local clubs. Do you handle all-over printing?",
      "Our jerseys are 100% polyester mesh. Is that okay for it?",
      "The base fabric is a dark navy. Does that change anything?",
      "We also have some cotton training tees. Can you use the same process for those?",
      "So what would you recommend for the cotton ones instead?",
      "Let's focus on the polyester jerseys. Do you do cut-panel or finished garments?",
      "We need player names and numbers on the back as well. Can that be included?",
      "What is your minimum order quantity for cut-panel sublimation?",
      "We need 500 pieces by 20th October. Is that achievable?",
      "What is your rate per jersey for that quantity?",
      "Can you match our club's exact Pantone colours?",
      "How do you handle colour matching - is there a sample stage?",
      "What does a sample cost and how long does it take?",
      "Will the print fade after repeated washing?",
      "Do you print on sleeves and collars too, or just the main panels?",
      "Our design has a sponsor logo that must be sharp. Any concerns with that?",
      "What file format do you need for an all-over design?",
      "Can you also do a few hoodies in the same design?",
      "Alright, I'd like to start a quotation for the 500 jerseys.",
      "Who should I contact to follow up on this?",
    ],
  },
  {
    name: "Mohammed Arif",
    company: "Arif Sourcing",
    service: "DTF Printing",
    profile: "Buying house sourcing for multiple apparel brands",
    turns: [
      "Good morning. I'm a sourcing agent working with several apparel brands.",
      "One of my clients has a photographic design with about 12 colours. Which process would you use for it?",
      "Why that one over screen printing?",
      "The garments are 60/40 cotton-poly fleece. Does DTF work on that?",
      "Does it hold up in industrial washing?",
      "How does the hand feel compare to screen printing?",
      "What artwork format should I send you for it?",
      "What resolution do you need for a photographic print?",
      "What is your price per piece for 2000 units?",
      "Is there a price break at higher quantities?",
      "What is the MOQ for DTF?",
      "Can you supply the transfers only, without applying them?",
      "How long would 2000 pieces take to produce?",
      "Do you provide UV DTF printing?",
      "Can DTF be combined with an embossed border around the print?",
      "My client needs compliance documentation for EU import. Can you provide that?",
      "Do you offer any wash test reports?",
      "Can we run a small trial of 50 pieces first?",
      "Right, let's begin a quotation for the 2000 piece order.",
      "What is the best way to reach your team for the technical details?",
    ],
  },
  {
    name: "Lakshmi Narayanan",
    company: "Lakshmi Label",
    service: "Silicone HD Printing",
    profile: "Fashion label wanting premium raised finishes on hoodies",
    turns: [
      "Hi, I run a fashion label and I'm looking for a premium finish on our hoodies.",
      "I want a raised glossy logo that feels high-end. What do you recommend?",
      "How thick or raised can the silicone actually go?",
      "Our hoodies are a heavy 400 GSM brushed fleece. Is that suitable?",
      "Can we get it in a matte finish instead of glossy?",
      "Can we add a puff texture around that same logo?",
      "Would that be one process or two separate ones?",
      "Does the silicone crack if the garment is stretched?",
      "What is the largest size we could run on the back panel?",
      "What is your price per piece for 300 hoodies?",
      "What's the minimum quantity you'd accept for this?",
      "Can I see a sample of the silicone finish before ordering?",
      "How long does sampling take for silicone HD?",
      "We're targeting a launch on 15th December. Can you meet that?",
      "Will the silicone print survive dry cleaning?",
      "Do you have certifications for the silicone inks used?",
      "Can you also do a small woven-look label print on the sleeve?",
      "What artwork do you need from our designer?",
      "Please prepare a quotation enquiry for 300 hoodies.",
      "How do I reach your team to discuss the finish in detail?",
    ],
  },
  {
    name: "Suresh Babu",
    company: "Babu Knitwear",
    service: "Screen Printing",
    profile: "Bulk knitwear manufacturer, repeat production runs",
    turns: [
      "Hello, we run a knitwear unit and need bulk printing for repeat orders.",
      "Most of our designs are 2 to 3 spot colours on cotton tees. What process suits that?",
      "What ink types can you work with for that?",
      "What is the difference between plastisol and water-based for us?",
      "Our buyer wants a very soft hand feel. Which one would you suggest?",
      "Can you do discharge printing on our dark garments?",
      "Our fabric is a reactive-dyed cotton. Any issue with discharge on that?",
      "How many colours can you print in one run?",
      "What is your price per piece for 5000 tees with 3 colours?",
      "Is there a separate screen setup charge?",
      "What is your MOQ for screen printing?",
      "How long would 5000 pieces take?",
      "Can you match a Pantone reference exactly?",
      "Will the print crack after washing?",
      "Can you add a high-density or puff effect to the same design?",
      "We also want a small neck label print. Is that a separate job?",
      "What artwork do you need for colour separations?",
      "Can we get a strike-off sample first?",
      "Let's start a quotation for the 5000 piece order.",
      "Who do I speak to about scheduling repeat runs?",
    ],
  },
  {
    name: "Anita Desai",
    company: "Anita Kidswear",
    service: "Specialty Printing",
    profile: "Kidswear brand wanting glitter, foil and puff effects",
    turns: [
      "Hi, we make kidswear and want some eye-catching finishes for a new collection.",
      "We're thinking glitter and foil effects. Do you offer those?",
      "What other special effects do you have besides those?",
      "Which of those would work best on a soft cotton jersey?",
      "Is glitter safe for children's garments?",
      "Can we combine foil with a puff outline?",
      "How durable is the foil after washing?",
      "Do you have reflective options? We want a safety jacket line too.",
      "Would reflective work on a nylon shell fabric?",
      "What is your price per piece for 800 pieces with foil?",
      "What is your minimum order for specialty effects?",
      "Can we sample two or three different effects before deciding?",
      "How long would that sampling take?",
      "We need the collection ready by 10th January. Is that possible?",
      "Do you have any child-safety or chemical compliance certificates?",
      "Can the glitter be applied only to part of the design?",
      "What is the smallest detail you can hold with flock?",
      "What artwork format should our designer supply?",
      "Please prepare a quotation for 800 pieces with foil and puff.",
      "How can I reach your team to review the samples?",
    ],
  },
  {
    name: "Karthik Raman",
    company: "Raman Uniforms",
    service: "Heat Transfer",
    profile: "Corporate uniform supplier needing names, numbers and badges",
    turns: [
      "Good afternoon. We supply corporate and school uniforms.",
      "We need names and numbers applied to garments. What is the best method?",
      "How is heat transfer different from direct printing?",
      "What transfer types do you offer?",
      "What is TPU transfer and where is it used?",
      "Our garments are a poly-cotton blend shirt. Any heat concerns?",
      "Can you supply transfers to us so we apply them ourselves?",
      "What temperature and pressure would we need for that?",
      "What is your price per transfer for 3000 pieces?",
      "What is the MOQ for transfers?",
      "How long would 3000 transfers take to produce?",
      "Can you do individual names, so every piece is different?",
      "Is there an extra charge for variable names?",
      "Will the transfer peel after repeated industrial laundering?",
      "Do you have durability test data for that?",
      "Can we also get a 3D raised effect on the badge?",
      "What artwork do you need for a name and number set?",
      "Can we trial 100 pieces first?",
      "Please start a quotation enquiry for the 3000 transfers.",
      "Who is the right person to contact about ongoing supply?",
    ],
  },
  {
    name: "Deepa Shankar",
    company: "Shankar Retail",
    service: "Sticker Printing",
    profile: "Retail brand needing garment, transfer and display stickers",
    turns: [
      "Hello, we're a retail brand and we need printed stickers.",
      "We need both garment stickers and some for our shop windows. Do you do both?",
      "What is the difference between a garment sticker and a transfer sticker?",
      "For the shop windows, what material would you use?",
      "Would those work on glass surfaces long term?",
      "Can you do die-cut shapes for our logo?",
      "What is the smallest sticker size you can produce?",
      "What is your price for 5000 garment stickers?",
      "What is the minimum order for stickers?",
      "How long would 5000 pieces take?",
      "Can the garment stickers be applied with heat by us?",
      "Will they stay on through a wash cycle?",
      "Do you offer any waterproof or outdoor-grade option?",
      "We need these before our store opening on 5th December. Possible?",
      "Can we see samples of the material first?",
      "What does a sample set cost?",
      "What artwork format do you need for die-cut shapes?",
      "Can you also print our care labels?",
      "Please prepare a quotation for 5000 garment stickers.",
      "How do I reach your team to approve the artwork?",
    ],
  },
  {
    name: "Vikram Joshi",
    company: "Joshi Premium Apparel",
    service: "Combination Printing",
    profile: "Premium brand wanting layered multi-technique designs",
    turns: [
      "Hi, we're a premium apparel brand looking for something more distinctive than a flat print.",
      "Can you combine more than one printing technique in a single design?",
      "What combinations do you typically do?",
      "We want a full-colour graphic framed by an embossed border. Is that possible?",
      "Which process would handle the colour part?",
      "How do you keep the two techniques aligned correctly?",
      "Does the order of the processes matter?",
      "Our fabric is a 100% cotton heavyweight tee. Any limitation?",
      "Would a combination design cost significantly more?",
      "What is your price per piece for 500 pieces of that?",
      "What is the MOQ for combination work?",
      "Would sampling be mandatory for this?",
      "How long does sampling take for a two-process design?",
      "We need bulk delivery by 28th February. Achievable?",
      "How durable is a combination print in washing?",
      "Could we add a foil accent as a third element?",
      "Is there a limit to how many techniques you can layer?",
      "What artwork do you need for a layered design?",
      "Please start a quotation for 500 combination pieces.",
      "Who can I speak to about the technical planning?",
    ],
  },
  {
    name: "Fatima Sheikh",
    company: "Sheikh Garments",
    service: "Placement Printing",
    profile: "Manufacturer needing prints at specific garment positions",
    turns: [
      "Hello, we manufacture casual wear and need prints at specific positions.",
      "What placements can you print on a t-shirt?",
      "We want a left chest logo and a large back print. Can you do both on one garment?",
      "Is there an extra cost for a second placement?",
      "What about sleeve and neck prints?",
      "Can you print on the bottom hem of joggers?",
      "How do you keep the placement consistent across sizes?",
      "Our size range is XS to 3XL. Does the print scale with the size?",
      "What is the largest back print you can do?",
      "What is your price per piece for 1500 pieces with two placements?",
      "What is the MOQ for a multi-placement order?",
      "Which printing process would you use for the back print?",
      "Would you recommend the same process for the chest logo?",
      "How long would 1500 pieces take to produce?",
      "Do you check placement accuracy before dispatch?",
      "Can we approve a placement sample first?",
      "We need them by 12th January. Is that feasible?",
      "What artwork and measurements do you need from us?",
      "Please prepare a quotation for 1500 pieces, two placements.",
      "How do I reach your team to confirm the placement details?",
    ],
  },
  {
    name: "Ganesh Murthy",
    company: "Murthy Textiles",
    service: "HD Printing",
    profile: "Streetwear producer wanting bold raised graphics",
    turns: [
      "Hi, we produce streetwear and want bold, raised graphics.",
      "What process gives the sharpest raised effect for big graphics?",
      "How is HD printing different from normal screen printing?",
      "And how does it compare to silicone HD?",
      "How high can the HD print be built up?",
      "Our design has large solid blocks and some numbers. Suitable?",
      "Some of the line work is quite thin. Will that hold?",
      "Our garments are 100% cotton heavyweight. Any issue?",
      "Can you do HD on fleece as well?",
      "What is your price per piece for 700 hoodies?",
      "What is your MOQ for HD printing?",
      "Do you need a sample approval before bulk?",
      "How long does HD sampling take?",
      "We need bulk by 25th January. Can you manage that?",
      "Will the raised print crack when stretched or washed?",
      "Can we combine HD with a silicone element in one design?",
      "Could we add foil on top of the HD?",
      "What artwork do you need for an HD build-up?",
      "Please start a quotation for 700 hoodies.",
      "Who should I contact to discuss the build height?",
    ],
  },
];

export default personas;
