import type { Metadata } from "next";
import { site } from "@/data/site";

type PageMeta = {
  title: string;
  description: string;
  path: string;
  image?: { url: string; width: number; height: number; alt: string };
  noIndex?: boolean;
};

export const absoluteUrl = (path = "/") => `${site.url}${path === "/" ? "" : path}`;

/**
 * Builds consistent per-page metadata: unique title, description,
 * canonical URL, Open Graph and Twitter cards.
 * The default OG image is generated by app/opengraph-image.tsx.
 */
const defaultImage = { url: "/opengraph-image", width: 1200, height: 630, alt: `${site.name} | ${site.tagline}` };

export function buildMetadata({ title, description, path, image, noIndex }: PageMeta): Metadata {
  // Setting `openGraph` replaces the inherited file-based image, so always provide one.
  const images = [image ?? defaultImage];
  return {
    title,
    description,
    alternates: { canonical: path },
    openGraph: {
      type: "website",
      locale: site.locale,
      siteName: site.name,
      url: path,
      title: `${title} | ${site.name}`,
      description,
      ...(images && { images }),
    },
    twitter: {
      card: "summary_large_image",
      title: `${title} | ${site.name}`,
      description,
      ...(images && { images: images.map((i) => i.url) }),
    },
    ...(noIndex && { robots: { index: false, follow: true } }),
  };
}
